# rolebinding-dmz.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bind-dmz-group
  namespace: dmz
subjects:
  - kind: Group
    name: dmz-group           # ← teleport role에서 내려오는 kubernetes_groups
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: dmz-reader
  apiGroup: rbac.authorization.k8s.io
