# rolebinding-app.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bind-app-group
  namespace: app
subjects:
  - kind: Group
    name: app-group           # ← teleport role에서 내려오는 kubernetes_groups
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: app-reader
  apiGroup: rbac.authorization.k8s.io
