apiVersion: v1
kind: Namespace
metadata:
  name: app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-service
  namespace: app
spec:
  replicas: 1
  selector: { matchLabels: { app: app-service } }
  template:
    metadata: { labels: { app: app-service } }
    spec:
      containers:
        - name: app
          image: hashicorp/http-echo:0.2.3
          args: ["-text=Hello from APP"]
          ports: [{ containerPort: 5678 }]
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: app
spec:
  selector: { app: app-service }
  ports: [{ port: 8080, targetPort: 5678 }]
