# db-role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: db-reader
  namespace: db
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "list", "watch"]
